export const BRANDS_LIST = {
  name: 'Brands',
  subcategories: [
    { label: 'A-COLD-WALL*', value: 'A_COLD_WALL' },
    { label: 'A.BOCCA', value: 'A_BOCCA' },
    { label: 'A.W.A.K.E. MODE', value: 'A_W_A_K_E_MODE' },
    { label: 'AAPE By A Bathing Ape', value: 'AAPE_BY_A_BATHING_APE' },
    { label: 'Abercrombie & Fitch', value: 'ABERCROMBIE_AND_FITCH' },
    { label: 'Abrand Jeans', value: 'ABRAND_JEANS' },
    { label: 'ABSOLUTE CULT', value: 'ABSOLUTE_CULT' },
    { label: 'ACBC', value: 'ACBC' },
    { label: 'adidas', value: 'ADIDAS' },
    {
      label: 'adidas by Stella McCartney',
      value: 'ADIDAS_BY_STELLA_MCCARTNEY'
    },
    { label: 'adidas Golf', value: 'ADIDAS_GOLF' },
    { label: 'adidas Originals', value: 'ADIDAS_ORIGINALS' },
    { label: 'adidas Performance', value: 'ADIDAS_PERFORMANCE' },
    { label: 'Adidas Sport', value: 'ADIDAS_SPORT' },
    { label: 'adidas Sportswear', value: 'ADIDAS_SPORTSWEAR' },
    { label: 'Adidas Terrex', value: 'ADIDAS_TERREX' },
    { label: 'Adieu', value: 'ADIEU' },
    { label: 'AG Jeans', value: 'AG_JEANS' },
    { label: 'AGNELLE', value: 'AGNELLE' },
    { label: 'Agolde', value: 'AGOLDE' },
    { label: 'Ahluwalia', value: 'AHLUWALIA' },
    { label: 'Aigle', value: 'AIGLE' },
    { label: 'AIGNER', value: 'AIGNER' },
    { label: "aim'n", value: 'AIMN' },
    { label: 'AKNVAS', value: 'AKNVAS' },
    { label: 'Alberta Ferretti', value: 'ALBERTA_FERRETTI' },
    { label: 'ALDO', value: 'ALDO' },
    { label: 'Alessandro Zavetti', value: 'ALESSANDRO_ZAVETTI' },
    { label: 'Alexander McQueen', value: 'ALEXANDER_MCQUEEN' },
    { label: 'Alexandre Birman', value: 'ALEXANDRE_BIRMAN' },
    { label: 'Alice + Olivia', value: 'ALICE_AND_OLIVIA' },
    { label: 'AllSaints', value: 'ALLSAINTS' },
    { label: 'Alpha Industries', value: 'ALPHA_INDUSTRIES' },
    { label: 'American Eagle', value: 'AMERICAN_EAGLE' },
    { label: 'American Vintage', value: 'AMERICAN_VINTAGE' },
    { label: 'Armani Exchange', value: 'ARMANI_EXCHANGE' },
    { label: 'ASICS', value: 'ASICS' },
    { label: 'ASPESI', value: 'ASPESI' },
    { label: 'Balenciaga', value: 'BALENCIAGA' },
    { label: 'Bally', value: 'BALLY' },
    { label: 'Barbour', value: 'BARBOUR' },
    { label: 'Belstaff', value: 'BELSTAFF' },
    { label: 'Ben Sherman', value: 'BEN_SHERMAN' },
    { label: 'Birkenstock', value: 'BIRKENSTOCK' },
    { label: 'BOSS', value: 'BOSS' },
    { label: 'Bottega Veneta', value: 'BOTTEGA_VENETA' },
    { label: 'Burberry', value: 'BURBERRY' },
    { label: 'Calvin Klein', value: 'CALVIN_KLEIN' },
    { label: 'Carhartt WIP', value: 'CARHARTT_WIP' },
    { label: 'Champion', value: 'CHAMPION' },
    { label: 'Clarks', value: 'CLARKS' },
    { label: 'Columbia', value: 'COLUMBIA' },
    { label: 'Converse', value: 'CONVERSE' },
    { label: 'Crocs', value: 'CROCS' },
    { label: 'DC Shoes', value: 'DC_SHOES' },
    { label: 'Dickies', value: 'DICKIES' },
    { label: 'Diesel', value: 'DIESEL' },
    { label: 'DKNY', value: 'DKNY' },
    { label: 'Dr. Martens', value: 'DR_MARTENS' },
    { label: 'Element', value: 'ELEMENT' },
    { label: 'Emporio Armani', value: 'EMPORIO_ARMANI' },
    { label: 'Evisu', value: 'EVISU' },
    { label: 'Fila', value: 'FILA' },
    { label: 'Fred Perry', value: 'FRED_PERRY' },
    { label: 'G-Star RAW', value: 'G_STAR_RAW' },
    { label: 'GANT', value: 'GANT' },
    { label: 'Giorgio Armani', value: 'GIORGIO_ARMANI' },
    { label: 'Gucci', value: 'GUCCI' },
    { label: 'Guess', value: 'GUESS' },
    { label: 'H&M', value: 'H_AND_M' },
    { label: 'Hackett London', value: 'HACKETT_LONDON' },
    { label: 'Helly Hansen', value: 'HELLY_HANSEN' },
    { label: 'HOKA', value: 'HOKA' },
    { label: 'Hugo Boss', value: 'HUGO_BOSS' },
    { label: 'Hurley', value: 'HURLEY' },
    { label: 'Jack & Jones', value: 'JACK_AND_JONES' },
    { label: 'Jordan', value: 'JORDAN' },
    { label: 'K-Swiss', value: 'K_SWISS' },
    { label: 'Kappa', value: 'KAPPA' },
    { label: 'Karl Lagerfeld', value: 'KARL_LAGERFELD' },
    { label: 'Lacoste', value: 'LACOSTE' },
    { label: "Levi's", value: 'LEVIS' },
    { label: 'Lyle & Scott', value: 'LYLE_AND_SCOTT' },
    { label: 'MM6 Maison Margiela', value: 'MM6_MAISON_MARGIELA' },
    { label: 'Marc Jacobs', value: 'MARC_JACOBS' },
    { label: "Marc O'Polo", value: 'MARC_O_POLO' },
    { label: 'Michael Kors', value: 'MICHAEL_KORS' },
    { label: 'New Balance', value: 'NEW_BALANCE' },
    { label: 'Nike', value: 'NIKE' },
    { label: 'North Face', value: 'NORTH_FACE' },
    { label: 'Oakley', value: 'OAKLEY' },
    { label: 'OnitsukaTiger', value: 'ONITSUKA_TIGER' },
    { label: 'Patagonia', value: 'PATAGONIA' },
    { label: 'Paul Smith', value: 'PAUL_SMITH' },
    { label: 'Prada', value: 'PRADA' },
    { label: 'Puma', value: 'PUMA' },
    { label: 'Quiksilver', value: 'QUIKSILVER' },
    { label: 'Ralph Lauren', value: 'RALPH_LAUREN' },
    { label: 'Rapha', value: 'RAPHA' },
    { label: 'Ray-Ban', value: 'RAY_BAN' },
    { label: 'Reebok', value: 'REEBOK' },
    { label: 'Salomon', value: 'SALOMON' },
    { label: 'Saucony', value: 'SAUCONY' },
    { label: 'Skechers', value: 'SKECHERS' },
    { label: 'Soulland', value: 'SOULLAND' },
    { label: 'Speedo', value: 'SPEEDO' },
    { label: 'Superdry', value: 'SUPERDRY' },
    { label: 'Ted Baker', value: 'TED_BAKER' },
    { label: 'The North Face', value: 'THE_NORTH_FACE' },
    { label: 'Timberland', value: 'TIMBERLAND' },
    { label: 'Tommy Hilfiger', value: 'TOMMY_HILFIGER' },
    { label: 'Under Armour', value: 'UNDER_ARMOUR' },
    { label: 'Vans', value: 'VANS' },
    { label: 'Versace', value: 'VERSACE' },
    { label: 'Volcom', value: 'VOLCOM' },
    { label: 'WOOYOUNGMI', value: 'WOOYOUNGMI' },
    { label: 'Wrangler', value: 'WRANGLER' },
    { label: 'Y-3', value: 'Y_3' },
    { label: 'ZEGNA', value: 'ZEGNA' }
  ]
} as const

// Types
export type BrandItem = {
  label: string
  value: string
}

export type BrandsList = {
  name: string
  subcategories: BrandItem[]
}
