export const BRANDS_LIST_FULL = {
  name: 'Brands',
  subcategories: [
    { label: 'A-COLD-WALL*', value: 'A_COLD_WALL' },
    { label: 'A.BOCCA', value: 'A_BOCCA' },
    { label: 'A.W.A.K.E. MODE', value: 'A_W_A_K_E_MODE' },
    { label: 'AAPE By A Bathing Ape', value: 'AAPE_BY_A_BATHING_APE' },
    { label: 'Abercrombie & Fitch', value: 'ABERCROMBIE_AND_FITCH' },
    { label: 'Abrand Jeans', value: 'ABRAND_JEANS' },
    { label: 'ABSOLUTE CULT', value: 'ABSOLUTE_CULT' },
    { label: 'ACBC', value: 'ACBC' },
    { label: 'adidas', value: 'ADIDAS' },
    {
      label: 'adidas by Stella McCartney',
      value: 'ADIDAS_BY_STELLA_MCCARTNEY'
    },
    { label: 'adidas Golf', value: 'ADIDAS_GOLF' },
    { label: 'adidas Originals', value: 'ADIDAS_ORIGINALS' },
    { label: 'adidas Performance', value: 'ADIDAS_PERFORMANCE' },
    { label: 'Adidas Sport', value: 'ADIDAS_SPORT' },
    { label: 'adidas Sportswear', value: 'ADIDAS_SPORTSWEAR' },
    { label: 'Adidas Terrex', value: 'ADIDAS_TERREX' },
    { label: 'Adieu', value: 'ADIEU' },
    { label: 'aerie', value: 'AERIE' },
    { label: 'AERON', value: 'AERON' },
    { label: 'AESTHER EKME', value: 'AESTHER_EKME' },
    { label: 'AG Jeans', value: 'AG_JEANS' },
    { label: 'Agent Provocateur', value: 'AGENT_PROVOCATEUR' },
    { label: 'AGNELLE', value: 'AGNELLE' },
    { label: 'Agolde', value: 'AGOLDE' },
    { label: 'Ahluwalia', value: 'AHLUWALIA' },
    { label: 'Aigle', value: 'AIGLE' },
    { label: 'AIGNER', value: 'AIGNER' },
    { label: "aim'n", value: 'AIMN' },
    { label: 'AKNVAS', value: 'AKNVAS' },
    { label: 'Alberta Ferretti', value: 'ALBERTA_FERRETTI' },
    { label: 'ALDO', value: 'ALDO' },
    { label: 'Alessandro Zavetti', value: 'ALESSANDRO_ZAVETTI' },
    { label: 'Alexander McQueen', value: 'ALEXANDER_MCQUEEN' },
    { label: 'Alexandre Birman', value: 'ALEXANDRE_BIRMAN' },
    { label: 'Alice + Olivia', value: 'ALICE_AND_OLIVIA' },
    { label: 'AllSaints', value: 'ALLSAINTS' },
    { label: 'Alma en Pena', value: 'ALMA_EN_PENA' },
    { label: 'ALOHAS', value: 'ALOHAS' },
    { label: 'Alpha Industries', value: 'ALPHA_INDUSTRIES' },
    { label: 'Altra', value: 'ALTRA' },
    { label: 'American Eagle', value: 'AMERICAN_EAGLE' },
    { label: 'American Vintage', value: 'AMERICAN_VINTAGE' },
    { label: 'AMMANN', value: 'AMMANN' },
    { label: 'AMUR', value: 'AMUR' },
    { label: 'Anaya with love', value: 'ANAYA_WITH_LOVE' },
    { label: 'Anchor & Crew', value: 'ANCHOR_AND_CREW' },
    { label: 'Ancuta Sarca', value: 'ANCUTA_SARCA' },
    { label: "Anderson's", value: 'ANDERSONS' },
    { label: 'ANDIATA', value: 'ANDIATA' },
    { label: 'ANDREA IYAMAH', value: 'ANDREA_IYAMAH' },
    { label: 'anello', value: 'ANELLO' },
    { label: 'ÁNGEL ALARCÓN', value: 'ANGEL_ALARCON' },
    { label: 'Angels', value: 'ANGELS' },
    { label: 'Anita', value: 'ANITA' },
    { label: 'Ann Summers', value: 'ANN_SUMMERS' },
    { label: 'Anna Field', value: 'ANNA_FIELD' },
    { label: 'Another Cotton Lab', value: 'ANOTHER_COTTON_LAB' },
    { label: 'Antony Morato', value: 'ANTONY_MORATO' },
    { label: 'Anya Hindmarch', value: 'ANYA_HINDMARCH' },
    { label: 'Apple', value: 'APPLE' },
    { label: 'April & Alex', value: 'APRIL_AND_ALEX' },
    { label: 'Araa Active', value: 'ARAA_ACTIVE' },
    { label: 'Arena', value: 'ARENA' },
    { label: 'ARIZONA LOVE', value: 'ARIZONA_LOVE' },
    { label: 'ARKET', value: 'ARKET' },
    { label: 'ARKK Copenhagen', value: 'ARKK_COPENHAGEN' },
    { label: 'Armani Exchange', value: 'ARMANI_EXCHANGE' },
    { label: 'Arnette', value: 'ARNETTE' },
    { label: 'arrels Barcelona', value: 'ARRELS_BARCELONA' },
    { label: 'ASICS', value: 'ASICS' },
    { label: 'ASPESI', value: 'ASPESI' },
    { label: 'Atelier de roupa', value: 'ATELIER_DE_ROUPA' },
    { label: 'Atelier Rêve', value: 'ATELIER_REVE' },
    { label: 'Athleta', value: 'ATHLETA' },
    { label: 'Aurélie Bidermann', value: 'AURELIE_BIDERMANN' },
    { label: 'AVAVAV', value: 'AVAVAV' },
    { label: 'Aware', value: 'AWARE' },
    { label: 'AZ Factory', value: 'AZ_FACTORY' },
    { label: 'b.belt', value: 'B_BELT' },
    { label: 'b.young', value: 'B_YOUNG' },
    { label: 'BALL', value: 'BALL' },
    { label: 'Bally', value: 'BALLY' },
    { label: 'Bamboo Basics', value: 'BAMBOO_BASICS' },
    { label: 'Banana Moon', value: 'BANANA_MOON' },
    { label: 'Barbour', value: 'BARBOUR' },
    { label: 'Bareen', value: 'BAREEN' },
    { label: 'Barrow', value: 'BARROW' },
    { label: 'Barts', value: 'BARTS' },
    { label: 'Baum und Pferdgarten', value: 'BAUM_UND_PFERDGARTEN' },
    { label: 'Bazix Republiq', value: 'BAZIX_REPUBLIQ' },
    { label: 'BDG Urban Outfitters', value: 'BDG_URBAN_OUTFITTERS' },
    { label: 'Bea Bongiasca', value: 'BEA_BONGIASCA' },
    { label: 'Beats', value: 'BEATS' },
    { label: 'Bec + Bridge', value: 'BEC_AND_BRIDGE' },
    { label: 'Becksöndergaard', value: 'BECKSONDERGAARD' },
    { label: 'Belstaff', value: 'BELSTAFF' },
    { label: 'Bench', value: 'BENCH' },
    { label: 'Berghaus', value: 'BERGHAUS' },
    { label: 'Bergstein', value: 'BERGSTEIN' },
    { label: 'Bettina Vermillon', value: 'BETTINA_VERMILLON' },
    { label: 'Bianco', value: 'BIANCO' },
    { label: 'Billabong', value: 'BILLABONG' },
    { label: 'Billi Bi', value: 'BILLI_BI' },
    { label: 'Billieblush', value: 'BILLIEBLUSH' },
    { label: 'Billionaire Boys Club', value: 'BILLIONAIRE_BOYS_CLUB' },
    { label: 'Birkenstock', value: 'BIRKENSTOCK' },
    { label: 'Bisgaard', value: 'BISGAARD' },
    { label: 'BITE Studios', value: 'BITE_STUDIOS' },
    { label: 'Björn Borg', value: 'BJORN_BORG' },
    { label: 'BLANCHE', value: 'BLANCHE' },
    { label: 'Blauer', value: 'BLAUER' },
    { label: 'Blend', value: 'BLEND' },
    { label: 'Blendshe', value: 'BLENDSHE' },
    { label: 'BLIZ', value: 'BLIZ' },
    { label: 'BLKVIS', value: 'BLKVIS' },
    { label: 'Blue by Betsey Johnson', value: 'BLUE_BY_BETSEY_JOHNSON' },
    { label: 'Blue Effect', value: 'BLUE_EFFECT' },
    { label: 'Bluebella', value: 'BLUEBELLA' },
    { label: 'BLUEMARBLE', value: 'BLUEMARBLE' },
    { label: 'Blundstone', value: 'BLUNDSTONE' },
    { label: 'Boglioli', value: 'BOGLIOLI' },
    { label: 'Bogner', value: 'BOGNER' },
    { label: 'BOILER ROOM', value: 'BOILER_ROOM' },
    { label: 'Bonastre', value: 'BONASTRE' },
    { label: 'Bonsai', value: 'BONSAI' },
    { label: 'Bonton', value: 'BONTON' },
    { label: 'Boob', value: 'BOOB' },
    { label: 'Borsalino', value: 'BORSALINO' },
    { label: 'BOSS', value: 'BOSS' },
    { label: 'Boux Avenue', value: 'BOUX_AVENUE' },
    { label: 'Brandit', value: 'BRANDIT' },
    { label: 'Brave Soul', value: 'BRAVE_SOUL' },
    { label: 'Brixton', value: 'BRIXTON' },
    { label: 'Brogger', value: 'BROGGER' },
    { label: 'Bronx', value: 'BRONX' },
    { label: 'Bruno Banani', value: 'BRUNO_BANANI' },
    { label: 'Brunotti', value: 'BRUNOTTI' },
    { label: 'Bruuns Bazaar', value: 'BRUUNS_BAZAAR' },
    { label: 'brx by BRONX', value: 'BRX_BY_BRONX' },
    { label: 'bStore', value: 'BSTORE' },
    { label: 'Buff', value: 'BUFF' },
    { label: 'Buffalo', value: 'BUFFALO' },
    { label: 'Buffalo London', value: 'BUFFALO_LONDON' },
    { label: 'bugatti', value: 'BUGATTI' },
    { label: 'Bullboxer', value: 'BULLBOXER' },
    { label: 'Bundgaard', value: 'BUNDGAARD' },
    { label: 'Burberry', value: 'BURBERRY' },
    { label: 'Burlington', value: 'BURLINGTON' },
    { label: 'Burton', value: 'BURTON' },
    { label: 'BY FAR', value: 'BY_FAR' },
    { label: 'By Malene Birger', value: 'BY_MALENE_BIRGER' },
    { label: 'Cabaia', value: 'CABAIA' },
    { label: 'Cache Coeur', value: 'CACHE_COEUR' },
    { label: 'CALANDO', value: 'CALANDO' },
    { label: 'Calida', value: 'CALIDA' },
    { label: 'Call it Spring', value: 'CALL_IT_SPRING' },
    { label: 'Callaway', value: 'CALLAWAY' },
    { label: 'Calvin Klein', value: 'CALVIN_KLEIN' },
    { label: 'Calzedonia', value: 'CALZEDONIA' },
    { label: 'Cam Cam Copenhagen', value: 'CAM_CAM_COPENHAGEN' },
    { label: 'camano', value: 'CAMANO' },
    { label: 'Camper', value: 'CAMPER' },
    { label: 'CAMPERLAB', value: 'CAMPERLAB' },
    { label: 'Canadian Classics', value: 'CANADIAN_CLASSICS' },
    { label: 'Candice Cooper', value: 'CANDICE_COOPER' },
    { label: 'Capezio', value: 'CAPEZIO' },
    { label: 'Caprice', value: 'CAPRICE' },
    { label: 'Carhartt WIP', value: 'CARHARTT_WIP' },
    { label: 'Carlo Colucci', value: 'CARLO_COLUCCI' },
    { label: 'Carne Bollente', value: 'CARNE_BOLLENTE' },
    { label: 'Carrera', value: 'CARRERA' },
    { label: 'Cars Jeans', value: 'CARS_JEANS' },
    { label: "Carter's", value: 'CARTERS' },
    { label: 'Cartoon', value: 'CARTOON' },
    { label: 'Casadei', value: 'CASADEI' },
    { label: 'Casall', value: 'CASALL' },
    { label: 'Casio', value: 'CASIO' },
    { label: 'Castañer', value: 'CASTANER' },
    { label: 'Castore', value: 'CASTORE' },
    { label: 'Casual Friday', value: 'CASUAL_FRIDAY' },
    { label: 'Cayler & Sons', value: 'CAYLER_AND_SONS' },
    { label: 'CDLP', value: 'CDLP' },
    { label: 'Ceceba', value: 'CECEBA' },
    { label: 'CeLaVi', value: 'CELAVI' },
    { label: 'Champion', value: 'CHAMPION' },
    { label: 'Champion Rochester', value: 'CHAMPION_ROCHESTER' },
    { label: 'Chantelle', value: 'CHANTELLE' },
    { label: 'Charlotte Chesnais', value: 'CHARLOTTE_CHESNAIS' },
    { label: 'Chekani', value: 'CHEKANI' },
    { label: 'Chelsea Paris', value: 'CHELSEA_PARIS' },
    { label: 'Chet Lo', value: 'CHET_LO' },
    { label: 'CHIARA FERRAGNI', value: 'CHIARA_FERRAGNI' },
    { label: 'Chie Mihara', value: 'CHIE_MIHARA' },
    { label: 'Chiemsee', value: 'CHIEMSEE' },
    { label: 'CHIMI', value: 'CHIMI' },
    { label: 'CHLOÉ', value: 'CHLOE' },
    { label: 'CHPO', value: 'CHPO' },
    { label: 'Ciele', value: 'CIELE' },
    { label: 'Cinq à Sept', value: 'CINQ_A_SEPT' },
    { label: 'Citizens of Humanity', value: 'CITIZENS_OF_HUMANITY' },
    { label: 'Clae', value: 'CLAE' },
    { label: "Claesen's", value: 'CLAESENS' },
    { label: 'Clarks', value: 'CLARKS' },
    { label: 'Clarks Originals', value: 'CLARKS_ORIGINALS' },
    { label: 'Clarks Unstructured', value: 'CLARKS_UNSTRUCTURED' },
    { label: 'Classics77', value: 'CLASSICS77' },
    { label: 'Cleptomanicx', value: 'CLEPTOMANICX' },
    { label: 'CLOSURE London', value: 'CLOSURE_LONDON' },
    { label: 'Cloud 5ive', value: 'CLOUD_5IVE' },
    { label: 'Cluse', value: 'CLUSE' },
    { label: 'CMP', value: 'CMP' },
    { label: 'COACH', value: 'COACH' },
    { label: 'Coastal', value: 'COASTAL' },
    { label: 'Coccinelle', value: 'COCCINELLE' },
    { label: 'Cole Haan', value: 'COLE_HAAN' },
    { label: 'Collina Strada', value: 'COLLINA_STRADA' },
    { label: 'Colmar', value: 'COLMAR' },
    { label: 'Colmar Originals', value: 'COLMAR_ORIGINALS' },
    { label: 'Color Kids', value: 'COLOR_KIDS' },
    { label: 'Colourful Rebel', value: 'COLOURFUL_REBEL' },
    { label: 'Columbia', value: 'COLUMBIA' },
    { label: 'Completedworks', value: 'COMPLETEDWORKS' },
    { label: 'Converse', value: 'CONVERSE' },
    { label: 'Copenhagen', value: 'COPENHAGEN' },
    { label: 'Copenhagen Muse', value: 'COPENHAGEN_MUSE' },
    { label: 'Cosabella', value: 'COSABELLA' },
    { label: 'Cotton On', value: 'COTTON_ON' },
    { label: 'Cotton On Body', value: 'COTTON_ON_BODY' },
    { label: 'Cotton On Petite', value: 'COTTON_ON_PETITE' },
    { label: 'Cras', value: 'CRAS' },
    { label: 'Cream', value: 'CREAM' },
    { label: 'Criminal Damage', value: 'CRIMINAL_DAMAGE' },
    { label: 'Cristiano Ronaldo CR7', value: 'CRISTIANO_RONALDO_CR7' },
    { label: 'Crocs', value: 'CROCS' },
    { label: 'Cult Gaia', value: 'CULT_GAIA' },
    { label: 'Custommade', value: 'CUSTOMMADE' },
    { label: 'Cyell', value: 'CYELL' },
    { label: 'D1 Milano', value: 'D1_MILANO' },
    { label: 'DADA', value: 'DADA' },
    { label: 'Daily Sports', value: 'DAILY_SPORTS' },
    { label: 'Dangerous DNGRS', value: 'DANGEROUS_DNGRS' },
    { label: 'Dare 2B', value: 'DARE_2B' },
    { label: 'DAVID CATALAN', value: 'DAVID_CATALAN' },
    { label: 'David Koma', value: 'DAVID_KOMA' },
    { label: 'Davida Cashmere', value: 'DAVIDA_CASHMERE' },
    { label: 'DAY Birger et Mikkelsen', value: 'DAY_BIRGER_ET_MIKKELSEN' },
    { label: 'DAY ET', value: 'DAY_ET' },
    { label: 'DC Shoes', value: 'DC_SHOES' },
    { label: 'Deadwood', value: 'DEADWOOD' },
    { label: 'DEAR FRANCES', value: 'DEAR_FRANCES' },
    { label: 'DeeZee', value: 'DEEZEE' },
    { label: 'DEF', value: 'DEF' },
    { label: 'Denham', value: 'DENHAM' },
    { label: 'Denim Project', value: 'DENIM_PROJECT' },
    { label: 'DENISA DOVALA', value: 'DENISA_DOVALA' },
    { label: 'Deniz Butik', value: 'DENIZ_BUTIK' },
    { label: 'DENTRO', value: 'DENTRO' },
    { label: 'DESIGNERS REMIX', value: 'DESIGNERS_REMIX' },
    { label: 'Desigual', value: 'DESIGUAL' },
    { label: 'Desires', value: 'DESIRES' },
    { label: 'Deuter', value: 'DEUTER' },
    { label: 'Dhruv Kapoor', value: 'DHRUV_KAPOOR' },
    { label: 'Diadora', value: 'DIADORA' },
    { label: 'Diane von Furstenberg', value: 'DIANE_VON_FURSTENBERG' },
    { label: 'Dice Kayek', value: 'DICE_KAYEK' },
    { label: 'Dickies', value: 'DICKIES' },
    { label: 'Didriksons', value: 'DIDRIKSONS' },
    { label: 'Diesel', value: 'DIESEL' },
    { label: 'DIM', value: 'DIM' },
    { label: 'DINARI JEWELS', value: 'DINARI_JEWELS' },
    { label: 'DIRTYPIGS', value: 'DIRTYPIGS' },
    { label: 'Disney', value: 'DISNEY' },
    { label: 'Divine Factory', value: 'DIVINE_FACTORY' },
    { label: "Djinn's", value: 'DJINNS' },
    { label: 'DKNY', value: 'DKNY' },
    { label: 'DKNY Intimates', value: 'DKNY_INTIMATES' },
    { label: 'DKNY Loungewear', value: 'DKNY_LOUNGEWEAR' },
    { label: 'DL1961', value: 'DL1961' },
    { label: 'DOCKERS', value: 'DOCKERS' },
    { label: 'Dockers by Gerli', value: 'DOCKERS_BY_GERLI' },
    { label: 'Dolce Vita', value: 'DOLCE_VITA' },
    { label: 'Dolce&Gabbana', value: 'DOLCE_AND_GABBANA' },
    { label: "Don't Waste Culture", value: 'DONT_WASTE_CULTURE' },
    { label: 'Dondup', value: 'DONDUP' },
    { label: 'Dora Larsen', value: 'DORA_LARSEN' },
    { label: 'DORINA', value: 'DORINA' },
    { label: 'Double A by Wood Wood', value: 'DOUBLE_A_BY_WOOD_WOOD' },
    { label: 'Doughnut', value: 'DOUGHNUT' },
    { label: 'Dr. Martens', value: 'DR_MARTENS' },
    { label: 'Dr.Denim', value: 'DR_DENIM' },
    { label: 'DRAGON DIFFUSION', value: 'DRAGON_DIFFUSION' },
    { label: 'Dropsize', value: 'DROPSIZE' },
    { label: 'DRYKORN', value: 'DRYKORN' },
    { label: 'Dsquared2', value: 'DSQUARED2' },
    { label: 'DSQUARED2 ICON', value: 'DSQUARED2_ICON' },
    { label: 'Dstrezzed', value: 'DSTREZZED' },
    { label: 'Duarte Hajime', value: 'DUARTE_HAJIME' },
    { label: 'Dunhill', value: 'DUNHILL' },
    { label: 'Dunlop', value: 'DUNLOP' },
    { label: 'Dynafit', value: 'DYNAFIT' },
    { label: 'EA7 Emporio Armani', value: 'EA7_EMPORIO_ARMANI' },
    { label: 'ECCO', value: 'ECCO' },
    { label: 'ECKHAUS LATTA', value: 'ECKHAUS_LATTA' },
    { label: 'ECKO', value: 'ECKO' },
    { label: 'ecko unltd.', value: 'ECKO_UNLTD' },
    { label: 'Ecoalf', value: 'ECOALF' },
    { label: 'edc by Esprit', value: 'EDC_BY_ESPRIT' },
    { label: 'EDITED', value: 'EDITED' },
    { label: 'EDITHMARCEL', value: 'EDITHMARCEL' },
    { label: 'Edwin', value: 'EDWIN' },
    { label: 'EIGHTYFIVE', value: 'EIGHTYFIVE' },
    { label: 'Eivy', value: 'EIVY' },
    { label: 'El Naturalista', value: 'EL_NATURALISTA' },
    { label: 'Element', value: 'ELEMENT' },
    { label: 'EleVen by Venus Williams', value: 'ELEVEN_BY_VENUS_WILLIAMS' },
    { label: 'ELHO', value: 'ELHO' },
    { label: 'Elisabetta Franchi', value: 'ELISABETTA_FRANCHI' },
    { label: 'Elleme', value: 'ELLEME' },
    { label: 'Ellesse', value: 'ELLESSE' },
    { label: 'Elomi', value: 'ELOMI' },
    { label: 'EMILI', value: 'EMILI' },
    { label: 'Emily van den Bergh', value: 'EMILY_VAN_DEN_BERGH' },
    { label: 'Emporio Armani', value: 'EMPORIO_ARMANI' },
    { label: 'EN FANT', value: 'EN_FANT' },
    { label: 'Endless', value: 'ENDLESS' },
    { label: 'Envii', value: 'ENVII' },
    { label: 'Erdem', value: 'ERDEM' },
    { label: 'és', value: 'ES' },
    { label: 'esmé studios', value: 'ESME_STUDIOS' },
    { label: "Espadrij l'originale", value: 'ESPADRIJ_ORIGINALE' },
    { label: 'Esprit', value: 'ESPRIT' },
    { label: 'Esprit Collection', value: 'ESPRIT_COLLECTION' },
    { label: 'Esprit Maternity', value: 'ESPRIT_MATERNITY' },
    { label: 'Essential Collective', value: 'ESSENTIAL_COLLECTIVE' },
    { label: 'Et Ochs', value: 'ET_OCHS' },
    { label: 'Etam', value: 'ETAM' },
    { label: 'Etnies', value: 'ETNIES' },
    { label: 'ETRO', value: 'ETRO' },
    { label: 'Études', value: 'ETUDES' },
    { label: 'Eugenia Kim', value: 'EUGENIA_KIM' },
    { label: 'Even&Odd', value: 'EVEN_AND_ODD' },
    { label: 'Evisu', value: 'EVISU' },
    { label: 'EVOKED VILA', value: 'EVOKED_VILA' },
    { label: 'Ewers', value: 'EWERS' },
    { label: 'EYTYS', value: 'EYTYS' },
    { label: 'Fabienne Chapot', value: 'FABIENNE_CHAPOT' },
    { label: 'Fabrizio', value: 'FABRIZIO' },
    { label: 'Faithfull the brand', value: 'FAITHFULL_THE_BRAND' },
    { label: 'FALKE', value: 'FALKE' },
    { label: 'Fanatics', value: 'FANATICS' },
    { label: 'Fantasie', value: 'FANTASIE' },
    { label: 'Farm Rio', value: 'FARM_RIO' },
    { label: 'Fast and Bright', value: 'FAST_AND_BRIGHT' },
    { label: 'FAVELA', value: 'FAVELA' },
    { label: 'FELICIOUS', value: 'FELICIOUS' },
    { label: 'FENTY x PUMA', value: 'FENTY_X_PUMA' },
    { label: 'FERRAGAMO', value: 'FERRAGAMO' },
    { label: 'Fête Impériale', value: 'FETE_IMPERIALE' },
    { label: 'Fila', value: 'FILA' },
    { label: 'Filippa K', value: 'FILIPPA_K' },
    { label: 'Filling Pieces', value: 'FILLING_PIECES' },
    { label: 'Finkid', value: 'FINKID' },
    { label: 'Fiorucci', value: 'FIORUCCI' },
    { label: 'FitFlop', value: 'FITFLOP' },
    { label: 'Five Ten', value: 'FIVE_TEN' },
    { label: 'Fjällräven', value: 'FJALLRAVEN' },
    { label: 'Fleur du Mal', value: 'FLEUR_DU_MAL' },
    { label: 'Flexfit', value: 'FLEXFIT' },
    { label: 'Flik Flak', value: 'FLIK_FLAK' },
    { label: 'forét', value: 'FORET' },
    { label: 'Forever Fit', value: 'FOREVER_FIT' },
    { label: 'Forever New', value: 'FOREVER_NEW' },
    { label: 'Forgotten Faces', value: 'FORGOTTEN_FACES' },
    { label: 'Former', value: 'FORMER' },
    { label: 'Forvert', value: 'FORVERT' },
    { label: 'Fossil', value: 'FOSSIL' },
    { label: 'FQ1924', value: 'FQ1924' },
    { label: 'FRAME', value: 'FRAME' },
    { label: 'Franchise', value: 'FRANCHISE' },
    { label: 'Frankies Bikinis', value: 'FRANKIES_BIKINIS' },
    { label: 'Fransa', value: 'FRANSA' },
    { label: 'Free People', value: 'FREE_PEOPLE' },
    { label: 'Freeman T. Porter', value: 'FREEMAN_T_PORTER' },
    { label: 'French Connection', value: 'FRENCH_CONNECTION' },
    { label: 'Freya', value: 'FREYA' },
    { label: 'Friboo', value: 'FRIBOO' },
    { label: 'Friendly Shoes', value: 'FRIENDLY_SHOES' },
    { label: 'Fritzi aus Preußen', value: 'FRITZI_AUS_PREUSSEN' },
    { label: 'Froddo', value: 'FRODDO' },
    { label: 'FROM FUTURE', value: 'FROM_FUTURE' },
    { label: 'Frugi', value: 'FRUGI' },
    { label: 'FTC Cashmere', value: 'FTC_CASHMERE' },
    { label: 'FUBU', value: 'FUBU' },
    { label: 'FUCHS SCHMITT', value: 'FUCHS_SCHMITT' },
    { label: 'Furla', value: 'FURLA' },
    { label: 'G-SHOCK', value: 'G_SHOCK' },
    { label: 'G-STAR', value: 'G_STAR' },
    { label: 'Gabba', value: 'GABBA' },
    { label: 'Gabor', value: 'GABOR' },
    { label: 'Gabor Comfort', value: 'GABOR_COMFORT' },
    { label: 'Gaimo', value: 'GAIMO' },
    { label: 'GANT', value: 'GANT' },
    { label: 'GAP', value: 'GAP' },
    { label: 'GAP Petite', value: 'GAP_PETITE' },
    { label: 'Gap Tall', value: 'GAP_TALL' },
    { label: 'Gaston Luga', value: 'GASTON_LUGA' },
    { label: 'GCDS', value: 'GCDS' },
    { label: 'GEDEBE', value: 'GEDEBE' },
    { label: 'Geox', value: 'GEOX' },
    { label: 'Gestuz', value: 'GESTUZ' },
    { label: 'GIABORGHINI', value: 'GIABORGHINI' },
    { label: 'Gianni Chiarini', value: 'GIANNI_CHIARINI' },
    { label: 'Gina Tricot', value: 'GINA_TRICOT' },
    { label: 'Giorgio Armani', value: 'GIORGIO_ARMANI' },
    { label: 'Gioseppo', value: 'GIOSEPPO' },
    { label: 'Gipsy by Mauritius', value: 'GIPSY_BY_MAURITIUS' },
    { label: 'Girlfriend Collective', value: 'GIRLFRIEND_COLLECTIVE' },
    { label: 'Giro', value: 'GIRO' },
    { label: 'Giuseppe Zanotti', value: 'GIUSEPPE_ZANOTTI' },
    { label: 'Glamorous', value: 'GLAMOROUS' },
    { label: 'Globe', value: 'GLOBE' },
    { label: 'Glorious Gangsta', value: 'GLORIOUS_GANGSTA' },
    { label: 'GmbH', value: 'GMBH' },
    { label: 'Goddiva', value: 'GODDIVA' },
    { label: 'Goldsign', value: 'GOLDSIGN' },
    { label: 'Golfino', value: 'GOLFINO' },
    { label: 'Good American', value: 'GOOD_AMERICAN' },
    { label: 'Goorin Bros', value: 'GOORIN_BROS' },
    { label: 'Gosoaky', value: 'GOSOAKY' },
    { label: 'Gossard', value: 'GOSSARD' },
    { label: 'Götzburg', value: 'GOTZBURG' },
    { label: 'Grass & Air', value: 'GRASS_AND_AIR' },
    { label: 'Grimey', value: 'GRIMEY' },
    { label: 'Grunt', value: 'GRUNT' },
    { label: 'Gucci', value: 'GUCCI' },
    { label: 'Guess', value: 'GUESS' },
    { label: 'Guess Jeans', value: 'GUESS_JEANS' },
    { label: 'Guess Originals', value: 'GUESS_ORIGINALS' },
    { label: 'HABEY CLUB', value: 'HABEY_CLUB' },
    {
      label: 'Hackett Aston Martin Racing',
      value: 'HACKETT_ASTON_MARTIN_RACING'
    },
    { label: 'Hackett London', value: 'HACKETT_LONDON' },
    { label: 'Halston', value: 'HALSTON' },
    { label: 'Han Kjøbenhavn', value: 'HAN_KJOBENHAVN' },
    { label: 'Hanwag', value: 'HANWAG' },
    { label: 'happy girls', value: 'HAPPY_GIRLS' },
    { label: 'Happy Mama', value: 'HAPPY_MAMA' },
    { label: 'Happy Shorts', value: 'HAPPY_SHORTS' },
    { label: 'Happy Socks', value: 'HAPPY_SOCKS' },
    { label: 'Harley Davidson', value: 'HARLEY_DAVIDSON' },
    { label: 'Havaianas', value: 'HAVAIANAS' },
    { label: 'Head', value: 'HEAD' },
    { label: 'Heathe', value: 'HEATHE' },
    { label: 'Heist Studios', value: 'HEIST_STUDIOS' },
    { label: 'Helly Hansen', value: 'HELLY_HANSEN' },
    { label: 'Helmstedt', value: 'HELMSTEDT' },
    { label: 'Helmut Lang', value: 'HELMUT_LANG' },
    { label: 'Henrik Vibskov', value: 'HENRIK_VIBSKOV' },
    { label: 'Henry Tiger', value: 'HENRY_TIGER' },
    { label: 'HERMAN&CO', value: 'HERMAN_AND_CO' },
    { label: 'Herrlicher', value: 'HERRLICHER' },
    { label: 'Hervé Léger', value: 'HERVE_LEGER' },
    { label: 'HI-TEC', value: 'HI_TEC' },
    { label: 'HI-TEC HTS74', value: 'HI_TEC_HTS74' },
    { label: 'Hofmann Copenhagen', value: 'HOFMANN_COPENHAGEN' },
    { label: 'HOKA', value: 'HOKA' },
    { label: 'Hollister Co.', value: 'HOLLISTER_CO' },
    { label: 'Holzweiler', value: 'HOLZWEILER' },
    { label: 'HOM', value: 'HOM' },
    { label: 'Homeboy', value: 'HOMEBOY' },
    { label: 'HOSBJERG', value: 'HOSBJERG' },
    { label: 'Houdini', value: 'HOUDINI' },
    { label: 'House of Holland', value: 'HOUSE_OF_HOLLAND' },
    { label: 'HOUSE OF JAFFA', value: 'HOUSE_OF_JAFFA' },
    { label: 'HUB', value: 'HUB' },
    { label: 'Hudson', value: 'HUDSON' },
    { label: 'HUF', value: 'HUF' },
    { label: 'HUGO', value: 'HUGO' },
    { label: 'HUGO KREIT', value: 'HUGO_KREIT' },
    { label: 'Hummel', value: 'HUMMEL' },
    { label: 'Hunkemöller', value: 'HUNKEMOLLER' },
    { label: 'Hunter ORIGINAL', value: 'HUNTER_ORIGINAL' },
    { label: 'Hust & Claire', value: 'HUST_AND_CLAIRE' },
    { label: 'Huttelihut', value: 'HUTTELIHUT' },
    { label: 'HVISK', value: 'HVISK' },
    { label: 'iBlues', value: 'IBLUES' },
    { label: 'ICANIWILL', value: 'ICANIWILL' },
    { label: 'Iceberg', value: 'ICEBERG' },
    { label: 'Icebreaker', value: 'ICEBREAKER' },
    { label: 'Icecream', value: 'ICECREAM' },
    { label: 'Icepeak', value: 'ICEPEAK' },
    { label: 'ICHI', value: 'ICHI' },
    { label: 'ICHI PETITE', value: 'ICHI_PETITE' },
    { label: 'Icon Brand', value: 'ICON_BRAND' },
    { label: 'Ida Sjöstedt', value: 'IDA_SJOSTEDT' },
    { label: 'iets frans...', value: 'IETS_FRANS' },
    { label: 'IKKS', value: 'IKKS' },
    { label: 'Il Gufo', value: 'IL_GUFO' },
    { label: 'Ilio Smeraldo', value: 'ILIO_SMERALDO' },
    { label: 'Ilse Jacobsen', value: 'ILSE_JACOBSEN' },
    { label: 'IN GOLD WE TRUST PARIS®', value: 'IN_GOLD_WE_TRUST_PARIS' },
    { label: 'INDICODE JEANS', value: 'INDICODE_JEANS' },
    { label: 'Intimissimi', value: 'INTIMISSIMI' },
    { label: 'InWear', value: 'INWEAR' },
    { label: 'Ioana Ciolacu', value: 'IOANA_CIOLACU' },
    { label: 'Ioannes', value: 'IOANNES' },
    { label: 'Iro', value: 'IRO' },
    { label: 'Isaac Dewhirst', value: 'ISAAC_DEWHIRST' },
    { label: 'Isabel Marant', value: 'ISABEL_MARANT' },
    { label: 'Ivy Copenhagen', value: 'IVY_COPENHAGEN' },
    { label: 'IVY OAK', value: 'IVY_OAK' },
    { label: 'IVY OAK BRIDAL', value: 'IVY_OAK_BRIDAL' },
    { label: 'J.LINDEBERG', value: 'J_LINDEBERG' },
    { label: 'J.LINDEBERG Sports', value: 'J_LINDEBERG_SPORTS' },
    { label: 'Jack & Jones', value: 'JACK_AND_JONES' },
    { label: 'Jack & Jones Junior', value: 'JACK_AND_JONES_JUNIOR' },
    { label: 'Jack & Jones Performance', value: 'JACK_AND_JONES_PERFORMANCE' },
    { label: 'Jack & Jones PREMIUM', value: 'JACK_AND_JONES_PREMIUM' },
    { label: 'Jack Wolfskin', value: 'JACK_WOLFSKIN' },
    { label: "Jack's Sportswear", value: 'JACKS_SPORTSWEAR' },
    { label: 'Jacker', value: 'JACKER' },
    { label: 'Jacky Baby', value: 'JACKY_BABY' },
    { label: 'Jacques Soloviere', value: 'JACQUES_SOLOVIERE' },
    { label: 'Jaded London', value: 'JADED_LONDON' },
    { label: 'JAKO', value: 'JAKO' },
    { label: 'Jana', value: 'JANA' },
    { label: 'JanSport', value: 'JANSPORT' },
    { label: 'Jarlo', value: 'JARLO' },
    { label: 'JDY', value: 'JDY' },
    { label: 'Jeffrey Campbell', value: 'JEFFREY_CAMPBELL' },
    { label: 'JELLY MALLOW', value: 'JELLY_MALLOW' },
    { label: 'Jellycat', value: 'JELLYCAT' },
    { label: 'JETTE', value: 'JETTE' },
    { label: 'Jimmy Choo', value: 'JIMMY_CHOO' },
    { label: 'JJXX', value: 'JJXX' },
    { label: 'Jockey', value: 'JOCKEY' },
    { label: 'Joha', value: 'JOHA' },
    { label: 'Johnstons of Elgin', value: 'JOHNSTONS_OF_ELGIN' },
    { label: 'JoJo Maman Bébé', value: 'JOJO_MAMAN_BEBE' },
    { label: 'Joma', value: 'JOMA' },
    { label: 'JOOP!', value: 'JOOP' },
    { label: 'JOOP! Jeans', value: 'JOOP_JEANS' },
    { label: 'Jordan', value: 'JORDAN' },
    { label: 'Joseph Ejiro', value: 'JOSEPH_EJIRO' },
    { label: 'Juicy Couture', value: 'JUICY_COUTURE' },
    { label: 'JULIETTA', value: 'JULIETTA' },
    { label: 'Just Cavalli', value: 'JUST_CAVALLI' },
    { label: 'Just Rhyse', value: 'JUST_RHYSE' },
    { label: 'JUSTINE CLENQUET', value: 'JUSTINE_CLENQUET' },
    { label: 'K-SWISS', value: 'K_SWISS' },
    { label: 'K-Way', value: 'K_WAY' },
    { label: 'K1X', value: 'K1X' },
    { label: 'Kabooki', value: 'KABOOKI' },
    { label: 'Kaffe', value: 'KAFFE' },
    { label: 'Kaffe Curve', value: 'KAFFE_CURVE' },
    { label: 'KangaROOS', value: 'KANGAROOS' },
    { label: 'Kangol', value: 'KANGOL' },
    { label: 'Kaotiko', value: 'KAOTIKO' },
    { label: 'Kappa', value: 'KAPPA' },
    { label: 'Kappa Gara', value: 'KAPPA_GARA' },
    { label: 'Kari Traa', value: 'KARI_TRAA' },
    { label: 'Karl Kani', value: 'KARL_KANI' },
    { label: 'KARL LAGERFELD', value: 'KARL_LAGERFELD' },
    { label: 'Karl Lagerfeld Jeans', value: 'KARL_LAGERFELD_JEANS' },
    { label: 'KARL LAGERFELD KIDS', value: 'KARL_LAGERFELD_KIDS' },
    { label: 'Kat Maconie', value: 'KAT_MACONIE' },
    { label: 'kate spade new york', value: 'KATE_SPADE_NEW_YORK' },
    { label: 'KAVU', value: 'KAVU' },
    { label: 'Keen', value: 'KEEN' },
    { label: 'Kempa', value: 'KEMPA' },
    { label: 'Kennel + Schmenger', value: 'KENNEL_AND_SCHMENGER' },
    { label: "Kentucky's Western", value: 'KENTUCKYS_WESTERN' },
    { label: 'khujo', value: 'KHUJO' },
    { label: 'Kickers', value: 'KICKERS' },
    { label: 'Kids ONLY', value: 'KIDS_ONLY' },
    { label: 'Kidzroom', value: 'KIDZROOM' },
    { label: 'Kigili', value: 'KIGILI' },
    { label: 'kimeze', value: 'KIMEZE' },
    { label: 'Kings Will Dream', value: 'KINGS_WILL_DREAM' },
    { label: 'Kjus', value: 'KJUS' },
    { label: 'KLABU', value: 'KLABU' },
    { label: 'Klättermusen', value: 'KLATTERMUSEN' },
    { label: 'KNITID', value: 'KNITID' },
    { label: 'KnowledgeCotton Apparel', value: 'KNOWLEDGECOTTON_APPAREL' },
    { label: 'Koi Footwear', value: 'KOI_FOOTWEAR' },
    { label: 'La Manso', value: 'LA_MANSO' },
    { label: 'La Perla', value: 'LA_PERLA' },
    { label: 'La Sportiva', value: 'LA_SPORTIVA' },
    { label: 'La Strada Unica', value: 'LA_STRADA_UNICA' },
    { label: 'Lacoste', value: 'LACOSTE' },
    { label: 'Lacoste Sport', value: 'LACOSTE_SPORT' },
    { label: 'Lakai', value: 'LAKAI' },
    { label: 'LAMODA', value: 'LAMODA' },
    { label: 'Lancel', value: 'LANCEL' },
    { label: 'LANVIN', value: 'LANVIN' },
    { label: 'LARDINI', value: 'LARDINI' },
    { label: 'LASCANA', value: 'LASCANA' },
    { label: 'Lässig', value: 'LASSIG' },
    { label: 'LÄST', value: 'LAST' },
    { label: 'Last Resort AB', value: 'LAST_RESORT_AB' },
    { label: 'Latelita', value: 'LATELITA' },
    { label: 'Laura Lombardi', value: 'LAURA_LOMBARDI' },
    { label: 'Lauren Ralph Lauren', value: 'LAUREN_RALPH_LAUREN' },
    { label: 'Lavaand', value: 'LAVAAND' },
    { label: 'le coq sportif', value: 'LE_COQ_SPORTIF' },
    { label: 'Le Petit Trou', value: 'LE_PETIT_TROU' },
    { label: 'Le Specs', value: 'LE_SPECS' },
    { label: 'Le Temps Des Cerises', value: 'LE_TEMPS_DES_CERISES' },
    { label: 'Lee', value: 'LEE' },
    { label: 'Legacies', value: 'LEGACIES' },
    { label: 'LEGACY STUDIOS', value: 'LEGACY_STUDIOS' },
    { label: 'LeGer by Lena Gercke', value: 'LEGER_BY_LENA_GERCKE' },
    { label: 'LEGO® kidswear', value: 'LEGO_KIDSWEAR' },
    { label: 'Lele Sadoughi', value: 'LELE_SADOUGHI' },
    { label: 'Les Benjamins', value: 'LES_BENJAMINS' },
    { label: 'Les Deux', value: 'LES_DEUX' },
    {
      label: 'Les Tropeziennes par M Belarbi',
      value: 'LES_TROPEZIENNES_PAR_M_BELARBI'
    },
    { label: "Levi's®", value: 'LEVIS' },
    { label: "Levi's® Gold Tab", value: 'LEVIS_GOLD_TAB' },
    { label: "Levi's® MOJ", value: 'LEVIS_MOJ' },
    { label: "Levi's® Plus", value: 'LEVIS_PLUS' },
    { label: "Levi's® Skateboarding", value: 'LEVIS_SKATEBOARDING' },
    { label: "Levi's® Workwear", value: 'LEVIS_WORKWEAR' },
    { label: 'Lexington', value: 'LEXINGTON' },
    { label: 'Libertine-Libertine', value: 'LIBERTINE_LIBERTINE' },
    { label: 'LICO', value: 'LICO' },
    { label: 'Liebeskind Berlin', value: 'LIEBESKIND_BERLIN' },
    { label: 'Liewood', value: 'LIEWOOD' },
    { label: "Lil'Boo", value: 'LIL_BOO' },
    { label: 'Lindbergh', value: 'LINDBERGH' },
    { label: 'Lindex', value: 'LINDEX' },
    { label: 'Liquorish', value: 'LIQUORISH' },
    { label: 'Lisou', value: 'LISOU' },
    { label: 'Little Liffner', value: 'LITTLE_LIFFNER' },
    { label: 'LIU JO', value: 'LIU_JO' },
    { label: 'Liu Jo Jeans', value: 'LIU_JO_JEANS' },
    { label: 'Living Kitzbühel', value: 'LIVING_KITZBUEHEL' },
    { label: 'Lloyd', value: 'LLOYD' },
    { label: "Lloyd Men's Belts", value: 'LLOYD_MENS_BELTS' },
    { label: 'Loeffler Randall', value: 'LOEFFLER_RANDALL' },
    { label: 'LÖFFLER', value: 'LOFFLER' },
    { label: 'LOGOSHIRT', value: 'LOGOSHIRT' },
    { label: 'LOIS Jeans', value: 'LOIS_JEANS' },
    { label: 'Lollys Laundry', value: 'LOLLYS_LAUNDRY' },
    { label: 'Lorette Colé Duprat', value: 'LORETTE_COLE_DUPRAT' },
    { label: 'Lost Youth', value: 'LOST_YOUTH' },
    { label: 'Lotto', value: 'LOTTO' },
    { label: 'Lousy Livin Underwear', value: 'LOUSY_LIVIN_UNDERWEAR' },
    { label: 'Love Moschino', value: 'LOVE_MOSCHINO' },
    { label: 'Love Scars', value: 'LOVE_SCARS' },
    { label: 'Lovechild', value: 'LOVECHILD' },
    { label: 'LOW LIGHTS STUDIOS®', value: 'LOW_LIGHTS_STUDIOS' },
    { label: 'Lowa', value: 'LOWA' },
    { label: 'LTB', value: 'LTB' },
    { label: 'Ludovic de Saint Sernin', value: 'LUDOVIC_DE_SAINT_SERNIN' },
    { label: 'Lukhanyo Mdingi', value: 'LUKHANYO_MDINGI' },
    { label: 'Lurchi', value: 'LURCHI' },
    { label: 'Lyle & Scott', value: 'LYLE_AND_SCOTT' },
    {
      label: "M'A KIDS by Marques ' Almeida",
      value: 'MA_KIDS_BY_MARQUES_ALMEIDA'
    },
    { label: 'Maanesten', value: 'MAANESTEN' },
    { label: 'Madden Girl', value: 'MADDEN_GIRL' },
    { label: 'Mads Nørgaard', value: 'MADS_NORGAARD' },
    { label: 'MAGIC Bodyfashion', value: 'MAGIC_BODYFASHION' },
    { label: 'Maguy de Chadirac', value: 'MAGUY_DE_CHADIRAC' },
    { label: 'Maidenform', value: 'MAIDENFORM' },
    { label: 'Maison Margiela', value: 'MAISON_MARGIELA' },
    { label: 'MAITREPIERRE', value: 'MAITREPIERRE' },
    { label: 'Makia', value: 'MAKIA' },
    { label: 'Malina', value: 'MALINA' },
    { label: 'MAMALICIOUS', value: 'MAMALICIOUS' },
    { label: 'Mammut', value: 'MAMMUT' },
    { label: 'Manastash', value: 'MANASTASH' },
    { label: 'Manebí', value: 'MANEBI' },
    { label: 'Mango', value: 'MANGO' },
    { label: 'Mango Kids', value: 'MANGO_KIDS' },
    { label: 'Mansur Gavriel', value: 'MANSUR_GAVRIEL' },
    { label: 'Mara Hoffman', value: 'MARA_HOFFMAN' },
    { label: 'Maradji', value: 'MARADJI' },
    { label: 'Marc Cain', value: 'MARC_CAIN' },
    { label: 'Marc Jacobs', value: 'MARC_JACOBS' },
    { label: 'Marc O Polo', value: 'MARC_O_POLO' },
    { label: 'Marc O Polo DENIM', value: 'MARC_O_POLO_DENIM' },
    { label: 'Marchesa', value: 'MARCHESA' },
    { label: 'Marchesa Notte', value: 'MARCHESA_NOTTE' },
    { label: 'Marchesa Rosa', value: 'MARCHESA_ROSA' },
    { label: 'MARCIANO BY GUESS', value: 'MARCIANO_BY_GUESS' },
    { label: 'Marco Tozzi', value: 'MARCO_TOZZI' },
    { label: 'Marella', value: 'MARELLA' },
    { label: 'Maria Black', value: 'MARIA_BLACK' },
    { label: 'Maria Luca', value: 'MARIA_LUCA' },
    { label: 'MARIJA KULUSIC', value: 'MARIJA_KULUSIC' },
    { label: 'Marikoo', value: 'MARIKOO' },
    { label: 'Marimekko', value: 'MARIMEKKO' },
    { label: 'Marina Rinaldi', value: 'MARINA_RINALDI' },
    { label: 'MARINE SERRE', value: 'MARINE_SERRE' },
    { label: 'Market', value: 'MARKET' },
    { label: 'MarMar Copenhagen', value: 'MARMAR_COPENHAGEN' },
    { label: 'Marni', value: 'MARNI' },
    { label: 'Mas Laus', value: 'MAS_LAUS' },
    { label: 'Mascara', value: 'MASCARA' },
    { label: "Mason's", value: 'MASONS' },
    { label: 'Massimo Dutti', value: 'MASSIMO_DUTTI' },
    { label: 'Materiel', value: 'MATERIEL' },
    { label: 'Maui Jim', value: 'MAUI_JIM' },
    { label: 'Mavi', value: 'MAVI' },
    { label: 'Max Mara', value: 'MAX_MARA' },
    { label: 'Max Mara Leisure', value: 'MAX_MARA_LEISURE' },
    { label: 'MAX&Co.', value: 'MAX_AND_CO' },
    { label: 'maximo', value: 'MAXIMO' },
    { label: 'mbyM', value: 'MBYM' },
    { label: 'MCM', value: 'MCM' },
    { label: 'MD Accessories', value: 'MD_ACCESSORIES' },
    { label: 'MELA', value: 'MELA' },
    { label: 'Melvin & Hamilton', value: 'MELVIN_AND_HAMILTON' },
    { label: 'Menbur', value: 'MENBUR' },
    { label: 'Mercader', value: 'MERCADER' },
    { label: 'Merchcode', value: 'MERCHCODE' },
    { label: 'Merrell', value: 'MERRELL' },
    { label: 'MESSI', value: 'MESSI' },
    { label: 'Michael Kors', value: 'MICHAEL_KORS' },
    { label: 'MICHAEL Michael Kors', value: 'MICHAEL_MICHAEL_KORS' },
    { label: 'MIISTA', value: 'MIISTA' },
    { label: 'MIKAGE SHIN', value: 'MIKAGE_SHIN' },
    { label: 'Milk it', value: 'MILK_IT' },
    { label: 'MILLE', value: 'MILLE' },
    { label: 'mine to five TOM TAILOR', value: 'MINE_TO_FIVE_TOM_TAILOR' },
    { label: 'Minelli', value: 'MINELLI' },
    { label: 'MINI A TURE', value: 'MINI_A_TURE' },
    { label: 'Mini Melissa', value: 'MINI_MELISSA' },
    { label: 'Mini Rodini', value: 'MINI_RODINI' },
    { label: 'Minimum', value: 'MINIMUM' },
    { label: 'Minymo', value: 'MINYMO' },
    { label: 'MISBHV', value: 'MISBHV' },
    { label: 'Missoni', value: 'MISSONI' },
    { label: 'Missoni Sport', value: 'MISSONI_SPORT' },
    { label: 'Mister Tee', value: 'MISTER_TEE' },
    { label: 'Mitchell & Ness', value: 'MITCHELL_AND_NESS' },
    { label: 'Mizuno', value: 'MIZUNO' },
    { label: 'MJ Gonzales', value: 'MJ_GONZALES' },
    { label: 'ML Monique Lhuillier', value: 'ML_MONIQUE_LHUILLIER' },
    { label: 'MM6 Maison Margiela', value: 'MM6_MAISON_MARGIELA' },
    { label: 'Modström', value: 'MODSTROM' },
    { label: 'MoEa', value: 'MOEA' },
    { label: 'Molly Bracken', value: 'MOLLY_BRACKEN' },
    { label: 'Molo', value: 'MOLO' },
    { label: 'Monica Vinader', value: 'MONICA_VINADER' },
    { label: 'Monki', value: 'MONKI' },
    { label: 'Monnalisa', value: 'MONNALISA' },
    { label: 'Mont Blanc', value: 'MONT_BLANC' },
    { label: 'Moon Boot', value: 'MOON_BOOT' },
    { label: 'Moon Chang', value: 'MOON_CHANG' },
    { label: 'More & More', value: 'MORE_AND_MORE' },
    {
      label: 'More Joy by Christopher Kane',
      value: 'MORE_JOY_BY_CHRISTOPHER_KANE'
    },
    { label: 'Morgan', value: 'MORGAN' },
    { label: 'MOROTAI', value: 'MOROTAI' },
    { label: 'Mos Mosh', value: 'MOS_MOSH' },
    { label: 'MOSCHINO', value: 'MOSCHINO' },
    { label: 'MOSCHINO JEANS', value: 'MOSCHINO_JEANS' },
    { label: 'MOSCHINO SWIM', value: 'MOSCHINO_SWIM' },
    { label: 'Moschino Underwear', value: 'MOSCHINO_UNDERWEAR' },
    { label: 'Mother', value: 'MOTHER' },
    { label: 'Mother of Pearl', value: 'MOTHER_OF_PEARL' },
    { label: 'Mou', value: 'MOU' },
    { label: 'MSCH Copenhagen', value: 'MSCH_COPENHAGEN' },
    { label: 'MSGM', value: 'MSGM' },
    { label: 'MSTRDS', value: 'MSTRDS' },
    { label: 'mtng', value: 'MTNG' },
    { label: 'MUNTHE', value: 'MUNTHE' },
    { label: 'Mustang', value: 'MUSTANG' },
    { label: 'My Mascara Curves', value: 'MY_MASCARA_CURVES' },
    { label: 'MY TRUE ME TOM TAILOR', value: 'MY_TRUE_ME_TOM_TAILOR' },
    { label: 'NA-KD', value: 'NA_KD' },
    { label: 'NAE Vegan Shoes', value: 'NAE_VEGAN_SHOES' },
    { label: 'NAF NAF', value: 'NAF_NAF' },
    { label: 'Name it', value: 'NAME_IT' },
    { label: 'Nanga', value: 'NANGA' },
    { label: 'Nannacay', value: 'NANNACAY' },
    { label: 'Nanushka', value: 'NANUSHKA' },
    { label: 'Napapijri', value: 'NAPAPIJRI' },
    { label: 'Naturino', value: 'NATURINO' },
    { label: 'Navahoo', value: 'NAVAHOO' },
    { label: 'NBA', value: 'NBA' },
    { label: 'Nebbia', value: 'NEBBIA' },
    { label: 'Needle & Thread', value: 'NEEDLE_AND_THREAD' },
    { label: 'Neil Barrett', value: 'NEIL_BARRETT' },
    { label: 'Neon & Nylon', value: 'NEON_AND_NYLON' },
    { label: 'NEOUS', value: 'NEOUS' },
    { label: 'Neuw', value: 'NEUW' },
    { label: 'Never Fully Dressed', value: 'NEVER_FULLY_DRESSED' },
    { label: 'New Balance', value: 'NEW_BALANCE' },
    { label: 'New Era', value: 'NEW_ERA' },
    { label: 'Nialaya', value: 'NIALAYA' },
    { label: 'Nicole Saldana', value: 'NICOLE_SALDANA' },
    { label: 'Night Addict', value: 'NIGHT_ADDICT' },
    { label: 'Nike', value: 'NIKE' },
    { label: 'Nike Golf', value: 'NIKE_GOLF' },
    { label: 'Nike Performance', value: 'NIKE_PERFORMANCE' },
    { label: 'Nike SB', value: 'NIKE_SB' },
    { label: 'Nike Sportswear', value: 'NIKE_SPORTSWEAR' },
    { label: 'Nike Swim', value: 'NIKE_SWIM' },
    { label: 'Nike Underwear', value: 'NIKE_UNDERWEAR' },
    { label: 'Nike Vision', value: 'NIKE_VISION' },
    { label: 'Nikolaj Storm', value: 'NIKOLAJ_STORM' },
    { label: 'NN.07', value: 'NN_07' },
    { label: 'Nodaleto', value: 'NODALETO' },
    { label: 'Noisy May', value: 'NOISY_MAY' },
    { label: 'Noon Goons', value: 'NOON_GOONS' },
    { label: 'Noppies', value: 'NOPPIES' },
    { label: 'Norma Kamali', value: 'NORMA_KAMALI' },
    { label: 'Norrøna', value: 'NORRONA' },
    { label: 'North Bend', value: 'NORTH_BEND' },
    { label: 'Nümph', value: 'NUMPH' },
    { label: 'NY CONCEPT', value: 'NY_CONCEPT' },
    { label: 'N°21', value: 'N_21' },
    { label: "O'Neill", value: 'O_NEILL' },
    { label: 'Oakley', value: 'OAKLEY' },
    { label: 'Obey Clothing', value: 'OBEY_CLOTHING' },
    { label: 'Object', value: 'OBJECT' },
    { label: 'ODLO', value: 'ODLO' },
    { label: 'OH APRIL', value: 'OH_APRIL' },
    { label: 'Olivia Rubin', value: 'OLIVIA_RUBIN' },
    { label: 'OLYMP', value: 'OLYMP' },
    { label: 'OLYMP Level Five', value: 'OLYMP_LEVEL_FIVE' },
    { label: 'OLYMP No. Six', value: 'OLYMP_NO_SIX' },
    { label: 'Olympia Le-Tan', value: 'OLYMPIA_LE_TAN' },
    { label: 'On Vacation', value: 'ON_VACATION' },
    { label: 'Onalaja', value: 'ONALAJA' },
    { label: 'Onitsuka Tiger', value: 'ONITSUKA_TIGER' },
    { label: 'ONLY', value: 'ONLY' },
    { label: 'Only & Sons', value: 'ONLY_AND_SONS' },
    { label: 'ONLY Carmakoma', value: 'ONLY_CARMAKOMA' },
    { label: 'ONLY MATERNITY', value: 'ONLY_MATERNITY' },
    { label: 'ONLY Play', value: 'ONLY_PLAY' },
    { label: 'OOSC', value: 'OOSC' },
    { label: 'OppoSuits', value: 'OPPOSUITS' },
    { label: 'Opus', value: 'OPUS' },
    { label: 'Orelia', value: 'ORELIA' },
    { label: 'Organic Basics', value: 'ORGANIC_BASICS' },
    { label: 'Origin Of Hearts', value: 'ORIGIN_OF_HEARTS' },
    { label: 'Original Penguin', value: 'ORIGINAL_PENGUIN' },
    { label: 'Osoi', value: 'OSOI' },
    { label: 'Outerstuff', value: 'OUTERSTUFF' },
    { label: 'OVS', value: 'OVS' },
    { label: 'OW Collection', value: 'OW_COLLECTION' },
    { label: 'Oxmo', value: 'OXMO' },
    { label: 'P.E Nation', value: 'PE_NATION' },
    { label: 'Paco Rabanne', value: 'PACO_RABANNE' },
    { label: 'Paige', value: 'PAIGE' },
    { label: 'Pal Zileri', value: 'PAL_ZILERI' },
    { label: 'Palladium', value: 'PALLADIUM' },
    { label: 'Palomo', value: 'PALOMO' },
    { label: 'Panafrica', value: 'PANAFRICA' },
    { label: 'Panama Jack', value: 'PANAMA_JACK' },
    { label: 'PARFOIS', value: 'PARFOIS' },
    { label: 'Part Two', value: 'PART_TWO' },
    { label: 'Passionata', value: 'PASSIONATA' },
    { label: 'Patagonia', value: 'PATAGONIA' },
    { label: 'Patrick Ewing', value: 'PATRICK_EWING' },
    { label: 'Patrizia Pepe', value: 'PATRIZIA_PEPE' },
    { label: 'Paul & Joe', value: 'PAUL_AND_JOE' },
    { label: 'Paul Green', value: 'PAUL_GREEN' },
    { label: 'Paul Smith', value: 'PAUL_SMITH' },
    { label: 'Pavement', value: 'PAVEMENT' },
    { label: 'Peak Performance', value: 'PEAK_PERFORMANCE' },
    { label: 'Pepe Jeans', value: 'PEPE_JEANS' },
    { label: 'Persol', value: 'PERSOL' },
    { label: 'Petit Bateau', value: 'PETIT_BATEAU' },
    { label: 'Petrol Industries', value: 'PETROL_INDUSTRIES' },
    { label: 'Philippe Model', value: 'PHILIPPE_MODEL' },
    { label: 'Pinko', value: 'PINKO' },
    { label: 'Polo Ralph Lauren', value: 'POLO_RALPH_LAUREN' },
    { label: 'Prada', value: 'PRADA' },
    { label: 'Prada Linea Rossa', value: 'PRADA_LINEA_ROSSA' },
    { label: 'Puma', value: 'PUMA' },
    { label: 'Quiksilver', value: 'QUIKSILVER' },
    { label: 'Rapha', value: 'RAPHA' },
    { label: 'Ray-Ban', value: 'RAY_BAN' },
    { label: 'Reebok', value: 'REEBOK' },
    { label: 'Reebok Classic', value: 'REEBOK_CLASSIC' },
    { label: 'River Island', value: 'RIVER_ISLAND' },
    { label: 'SAINT LAURENT', value: 'SAINT_LAURENT' },
    { label: 'Salomon', value: 'SALOMON' },
    { label: 'Salvatore Ferragamo', value: 'SALVATORE_FERRAGAMO' },
    { label: 'Saucony', value: 'SAUCONY' },
    { label: 'Soulland', value: 'SOULLAND' },
    { label: 'Speedo', value: 'SPEEDO' },
    { label: 'Superdry', value: 'SUPERDRY' },
    { label: 'Ted Baker', value: 'TED_BAKER' },
    { label: 'The North Face', value: 'THE_NORTH_FACE' },
    { label: 'Timberland', value: 'TIMBERLAND' },
    { label: 'Tommy Hilfiger', value: 'TOMMY_HILFIGER' },
    { label: 'Under Armour', value: 'UNDER_ARMOUR' },
    { label: 'Uniqlo', value: 'UNIQLO' },
    { label: 'United Colors of Benetton', value: 'UNITED_COLORS_OF_BENETTON' },
    { label: 'Vans', value: 'VANS' },
    { label: 'Versace', value: 'VERSACE' },
    { label: 'Versace Jeans Couture', value: 'VERSACE_JEANS_COUTURE' },
    { label: 'Volcom', value: 'VOLCOM' },
    { label: 'WOOYOUNGMI', value: 'WOOYOUNGMI' },
    { label: 'Wrangler', value: 'WRANGLER' },
    { label: 'Y-3', value: 'Y_3' },
    { label: 'ZEGNA', value: 'ZEGNA' },
    { label: 'Zehlendorf1', value: 'ZEHLENDORF1' },
    { label: 'ZIGGY CHEN', value: 'ZIGGY_CHEN' }
  ]
} as const

export type BrandItemFull = {
  label: string
  value: string
}

export type BrandsListFull = {
  name: string
  subcategories: BrandItemFull[]
}
